[package]
name = "fft-wasm"
version = "0.1.0"
authors = [ "Victor Magalhães <victorhfmag@gmail.com>" ]

[dependencies]
num = "0.2.0"
wasm-bindgen = "0.2.38"
cfg-if = "0.1.7"
console_error_panic_hook = "0.1.6"

[lib]
crate-type = [ "cdylib" ]
